### ISSUE TITLE
Add support for choosing minors and additionals

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyfe#3]
Things which would make this an all rounder app, the only thing on would require during subject registration:

- [x] Support for Minor in CLI

And ofcourse, the webapp

**Comment by ShreyaBose04** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by proffapt** [comment]
Great! @ashwinpra will be helping you out on this issue.

**Comment by ashwinpra** [comment]
> Support for additionals
- For now, nothing extra needs to be done, as the script already scrapes whatever course you are free to choose (based on vacant slots), and these courses could be chosen as either additional or breadth. This would be more relevant once the webapp is developed so that there can be a clear distinguishment between electives and additionals in your generated timetable (see 3rd point [here](https://github.com/metakgp/gyfe/issues/2#issue-1922651707))
> Support for minors
- To the best of my knowledge, there's no better way than manually defining the required courses, which can be found in ERP from `Academic -> Subjects -> Minor Curricula (New Curricula)` (it's a PDF). Something similar has been done in `what-slot` [here](https://github.com/metakgp/what-slot/blob/3539fc5538d264822516a6810c1a266aa0255a81/minor.json)
- Once the courses are defined, some method can be used to specify in the final output (list of all courses) the courses that are required for a certain minor (for example, a new column could be added to display this info)
>  Reflect the above on webapp
- This can be ignored _for now_ as the webapp is still under development

**Comment by proffapt** [comment]
- [ ] Support for Additional in Webapp
- [ ] Support for Minor in Webapp

Will be listed in #2
